config/routes.rb
Rails.application.routes.draw do

  resources :integrations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "data_feeds#home"
  root to: "data_feeds#names"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_feed.rb
class DataFeed < ApplicationRecord

	before_save :etd_record_key

	def etd_record_key
		# For every instance, combine PPID, acad_career, acad_program and save it in etd_record_key column
		self.etd_record_key = "#{public_person_ID}-#{acad_career_code}-#{acad_program_code}" 
	end
end

app/models/integration.rb
class Integration < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/data_feeds_controller.rb
class DataFeedsController < ApplicationController
  before_action :filter_ip_address
  
  def home
  end


  private
    
    def filter_ip_address
    	requestor = Integration.where(ip: request.remote_ip).present?
    	head :unauthorized unless requestor
    end
end

app/controllers/integrations_controller.rb
class IntegrationsController < ApplicationController
  before_action :set_integration, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  before_action :authenticate_requestor

  # GET /integrations
  # GET /integrations.json
  def index
    @integrations = Integration.all
  end

  # GET /integrations/1
  # GET /integrations/1.json
  def show
  end

  # GET /integrations/new
  def new
    @integration = Integration.new
  end

  # GET /integrations/1/edit
  def edit
  end

  # POST /integrations
  # POST /integrations.json
  def create
    @integration = Integration.new(integration_params)

    respond_to do |format|
      if @integration.save
        format.html { redirect_to @integration, notice: 'Integration was successfully created.' }
        format.json { render :show, status: :created, location: @integration }
      else
        format.html { render :new }
        format.json { render json: @integration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /integrations/1
  # PATCH/PUT /integrations/1.json
  def update
    respond_to do |format|
      if @integration.update(integration_params)
        format.html { redirect_to @integration, notice: 'Integration was successfully updated.' }
        format.json { render :show, status: :ok, location: @integration }
      else
        format.html { render :edit }
        format.json { render json: @integration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /integrations/1
  # DELETE /integrations/1.json
  def destroy
    @integration.destroy
    respond_to do |format|
      format.html { redirect_to integrations_url, notice: 'Integration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_integration
      @integration = Integration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def integration_params
      params.fetch(:integration, {})
    end

    def authenticate_requestor
    	# Check if user is authenticated or IP matching
    	redirect_to(new_user_session_url) unless (user_signed_in?) # || IP matching
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_feeds_helper.rb
module DataFeedsHelper
end

app/views/data_feeds/home.html.erb
<h1>DataFeeds#home</h1>
<p>Find me in app/views/data_feeds/home.html.erb</p>

app/views/integrations/_form.html.erb
<%= form_with(model: integration, local: true) do |form| %>
  <% if integration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(integration.errors.count, "error") %> prohibited this integration from being saved:</h2>

      <ul>
      <% integration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/integrations/edit.html.erb
<h1>Editing Integration</h1>

<%= render 'form', integration: @integration %>

<%= link_to 'Show', @integration %> |
<%= link_to 'Back', integrations_path %>

app/views/integrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Integrations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @integrations.each do |integration| %>
      <tr>
        <td><%= link_to 'Show', integration %></td>
        <td><%= link_to 'Edit', edit_integration_path(integration) %></td>
        <td><%= link_to 'Destroy', integration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Integration', new_integration_path %>

app/views/integrations/new.html.erb
<h1>New Integration</h1>

<%= render 'form', integration: @integration %>

<%= link_to 'Back', integrations_path %>

app/views/integrations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_integration_path(@integration) %> |
<%= link_to 'Back', integrations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataFeeds</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>
    <%= yield %>
  </body>
</html>